---
# Install Giltab Runner
- name: Install Giltab Runner
  block:

    # Update System

    - name: Update System
      apt:
        update_cache: true
        cache_valid_time: 86400

    # Install Gitlab Runner

    - name: Get Gitlab repository installation script
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: /tmp/gitlab-runner.script.deb.sh
        mode: 0744

    - name: Install Gitlab repository
      command: >
        bash /tmp/gitlab-runner.script.deb.sh
      args:
        creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

    - name: Set gitlab_runner_package_name
      set_fact:
        gitlab_runner_package: gitlab-runner
        gitlab_runner_package_state: latest
      when: gitlab_runner_package_version is not defined

    - name: Install GitLab Runner
      apt:
        name: gitlab-runner
        state: latest
