---
- name: Install Gitlab Runner
  hosts: all
  become: yes
  vars_files:
    - /home/ivankarpenko/devops/ansible/setup-aws-bastion-server/setup/roles/gitlab-runner-install/vars/main.yml

  roles:
    - gitlab-runner-install
    