---
- name: Install Docker Machine
  hosts: all
  become: yes
  vars_files:
    - /home/ivankarpenko/devops/ansible/setup-aws-bastion-server/setup/roles/docker-machine-install/vars/main.yml
  
  roles:
    - docker-machine-install
        
