---
- name: Register Gitlab Runner
  hosts: all
  become: yes
  vars_files:
    - /home/ivankarpenko/devops/ansible/setup-aws-bastion-server/setup/roles/gitlab-runner-register/vars/main.yml

  roles:
    - gitlab-runner-register
